### PR TITLE
Upgrade to OCaml 4.08+beta2

### PR DESCRIPTION
**Pull request by jhwoodyatt**
For reference, this is what **OCaml 4.08+beta2** seems to require (issue #69).

### CODE REVIEW

**Comment by jhwoodyatt** [comment]
I don't understand why Travis CI is complaining, and I don't have the time to investigate.

**Comment by hhugo** [comment]
cc @xclerc

**Comment by kit-ty-kate** [comment]
@jhwoodyatt I opened a PR on your fork to fix travis: https://github.com/jhwoodyatt/ppx_tools/pull/1

**Comment by kit-ty-kate** [comment]
all green. cc @alainfrisch @gasche (not sure who's maintaining this)

**Comment by gasche** [comment]
I know I'm not, but maybe I can try to have a look later in the week if nobody has stepped up. (cc @alainfrisch @nojb @xclerc @diml)

**Comment by gasche** [comment]
It's embarrassing that I don't know how to check the list of people with merge rights (to me or to the Github interface), but it may be that only @alainfrish is in this set. I would warmly recommend to add @nojb to it, though :-)

**Comment by Drup** [comment]
I have merge rights! But I can't add more people to the repository.
I also have very little time right now, so I won't be able to make a release myself for a few weeks.

**Comment by gasche** [comment]
While testing the master branch on 4.08 I found a small issue -- the generated code still mentions Pervasives -- for which I propose a fix in #72. Would someone look at it and consider merging it?

**Comment by XVilka** [comment]
Shouldn't be this merged one already? It is pretty obvious it is good one.

**Comment by hhugo** [comment]
I believe metaquot is currently broken with this feature.
One should ignore `pexp_loc_stack`, `ptyp_loc_stack`, `ppat_loc_stack` when generating patterns on the ast. see what's done for location and attributes: https://github.com/ocaml-ppx/ppx_tools/blob/master/ppx_metaquot.ml#L175

Also see the patch in ppx_tools_versionned https://github.com/ocaml-ppx/ppx_tools_versioned/pull/22/files#diff-7ab097557bb7183454f885e4595acc38R180

**Pull request merged**
