### PR TITLE
4.06 support

### PR DESCRIPTION
**Pull request by gasche**
This updates ppx_tools to compile correctly under 4.06.

(As I'm submitting this PR I realize that I may not have updated the lifter, I only fixed the build errors. I will look at it right now, so consider the PR as a work-in-progress for the next hour)

### CODE REVIEW

**Comment by alainfrisch** [comment]
> I may not have updated the lifter

You mean, ast_lifter.ml.  This file is generated by the build system, so this should be fine I think.

**Comment by gasche** [comment]
Ok, good news! (I'm not familiar with the ppx_tools internals.) So code-wise the present PR should be enough?

Travis CI fails because I did not touch the travis.yml file -- I noticed that the "right way" for it is to test 4.06 under an upstream 4.06 branch, and I will let the repo maintainer (you) do the branch-creation etc. But I should still have edited the file so that master uses 4.06(+beta2 for now?), correct? I will add an extra commit for this.

**Comment by gasche** [comment]
(thanks @avsm for the 4.06.0 dockerfiles, I was surprised to see they already exist.)

**Comment by gasche** [comment]
@alainfrisch travis now passes correctly. Is there anything else I need to do on my end?

**Comment by gasche** [comment]
Thanks! Eventually it would be helpful to have a ppx_tools release for 4.06. I can take care of the opam-repository publishing part if you want.

**Comment by alainfrisch** [comment]
https://github.com/ocaml/opam-repository/pull/10525

**Pull request merged**
